sudo: required
services: docker
before_install:
    # - gem install bundler -v 2.5.8
    - docker-compose up --build -d
    - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com
script:
    - docker-compose run --rm --env 'RAILS_ENV=test' web bundle exec rails db:create
    - docker-compose run --rm --env 'RAILS_ENV=test' web bundle exec rails db:migrate
    - docker-compose run --rm --env 'RAILS_ENV=test' web bundle exec rails test

deploy:
    provider: script
    script:
        docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku run --app $HEROKU_APP_NAME rails db:migrate;
    on:
        branch: main
