sudo: required
services: docker
before_install:
    - gem install bundler -v 2.4.22
    - docker-compose up --build -d
script:
    - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
    - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
    - docker-compose exec --env 'RAILS_ENV=test' web rails test
