sudo: required
services: docker
before_install:
    - gem install bundler -v 2.4.22
    - docker-compose up --build -d
script:
    - docker-compose run --rm --env 'RAILS_ENV=test' web bundle exec rails db:create
    - docker-compose run --rm --env 'RAILS_ENV=test' web bundle exec rails db:migrate
    - docker-compose run --rm --env 'RAILS_ENV=test' web bundle exec rails test
