sudo: required
services: docker

script:
    - docker-compose run --rm --env RAILS_ENV=test web rails db:create
    - docker-compose run --rm --env RAILS_ENV=test web rails db:migrate
    - docker-compose run --rm --env RAILS_ENV=test web rails test
